version: 2.1
jobs:
  push:
   docker:
      - image: ubuntu:18.04
   steps:
      - run:
          name: init
          command: |
           apt-get -y update && apt-get -y upgrade && apt-get -y install python git curl wget repo
           python -m ensurepip --default-pip
           python -m pip install python-telegram
           git clone https://github.com/Chityanj/ota_scripts ota/
           cd ota/
           ./push.sh
workflows:
  version: 2.1
  cooking:
    jobs:
      - push
